@startuml
class StateManager {
    + gameOver : GameOver
    + victory : Victory
    + GameOver() : void
    + Victory() : void
    - MenuSetup() : void
    - MenuQuit() : void
}
StateManager --> "1" GameOver
StateManager --> "   1" Victory
@enduml
