@startuml
class SettingMenu {
    + audioMixer : AudioMixer
    + volSlider : GameObject
    + sensiSlider : GameObject
    - Awake() : void
    + SetVolume(volume:float) : void
    + SetQuality(qualityIndex:int) : void
    + SetFullscreen(isFullScreen:bool) : void
    + SetSensitivity(sensitivity:float) : void
}
SettingMenu ..> StaticSettings
@enduml
